'use strict'

exports.name = 'SCH'

exports.fields = [
  'SegmentType'
, 'PlacerApointmentID'
, 'FillerApointmentID'
, 'OccurenceNumber'
, 'PlaceGroupNumber'
, 'DelayedAcknowledgementType'
, 'ScheduleID'
, 'EventReason'
, 'AppointmentReason'
, 'AppointmentType'
, 'AppointmentDuration'
, 'AppointmentDurationUnits'
, 'AppointmentTimingQuantity'
, 'PlacerContactPerson'
, 'PlacerContactPhoneNumber'
, 'PlacerContactAddress'
, 'PlacerContactLocation'
, 'FillerContactPerson'
, 'FillerContactPhoneNumber'
, 'FillerContactAddress'
, 'FillerContactLocation'
, 'EnteredByPerson'
, 'EnteredByPhoneNumber'
, 'ParentPlacerAppointmentID'
, 'ParentFillerAppointmentID'
, 'FillerStatusCode'
, 'PlacerOrderNumber'
, 'FillerOrderNumber'
]
